import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import {
  AmazonController,
  AmazonModule,
  AmazonService,
  ChannelController,
  ChannelModule,
  ChannelService,
  SkuController,
  SkuModule,
  SkuService,
  UserModule,
  GoogleModule,
  GoogleController,
  GoogleService,
  NotificationModule,
  NotificationService,
  NotificationController,
  DatesMetaDataModule,
  DatesMetaDataService,
  DashboardModule,
  DashboardController,
  ReportsModule,
  ReportsService,
  CatalogModule,
  CatalogController,
  CatalogService,
} from './modules';

@Module({
  imports: [
    UserModule,
    ChannelModule,
    SkuModule,
    AmazonModule,
    GoogleModule,
    NotificationModule,
    DatesMetaDataModule,
    DashboardModule,
    ReportsModule,
    CatalogModule,
  ],
  controllers: [
    AppController,
    ChannelController,
    SkuController,
    AmazonController,
    GoogleController,
    NotificationController,
    DashboardController,
    CatalogController,
  ],
  providers: [
    AppService,
    ChannelService,
    SkuService,
    AmazonService,
    GoogleService,
    NotificationService,
    DatesMetaDataService,
    ReportsService,
    CatalogService,
  ],
})
export class AppModule {}
